name: Push-Triggers

on:
  push:
    branches:
    - master
    - develop
    - qa-develop
    - 'release-**'
  release:
    types: [published]
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
    - master
    - develop
    - qa-develop
    - 'release-**'

jobs:
  build-android:
    uses: mosip/kattu/.github/workflows/android-build.yml@master
    with:
      NODE_VERSION: "18.x"
      JAVA_VERSION: "17"
      KEYSTORE_ALIAS: androidbuildkey
      KEYSTORE_PASSWORD: 'password'
      SERVICE_LOCATION: '.'
      ANDROID_SERVICE_LOCATION: 'android'
      BUILD_SCRIPT_LOCATION: 'scripts'
      SCRIPT_NAME: './android-build.sh'
      UPLOAD_TO_ACTIONS: 'false'

  build-ios:
    uses: mosip/kattu/.github/workflows/ios-build.yml@master
    with:
      NODE_VERSION: "18.x"
      SERVICE_LOCATION: '.'
      IOS_SERVICE_LOCATION: 'ios'
      SCRIPT_NAME: "fastlane ios_app_build"

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6.0.0
        with:
          node-version: '18.x'
          cache: 'npm'
      - name: Install the dependencies
        run: npm install
      - name: Build the project
        run: npm run build
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,author,commit,workflow,job
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_INJI_TEAM }}
        if: failure()

  sonar-check-on-push:
    name: Sonar check
    if: ${{ github.event_name != 'pull_request' }}
    needs: [build-android, build-ios, run-tests]
    uses: mosip/kattu/.github/workflows/npm-sonar-analysis.yml@master-java21
    with:
      SERVICE_LOCATION: '.'
      NODE_VERSION: '18.x'
      NPM_BUILD_TYPE: 'BOB'
      SONAR_SOURCES: '.'
      SONAR_TESTS: '.'
      SONAR_TEST_INCLUSIONS: '**/*.test.ts, **/*.test.tsx'
      SONAR_EXCLUSIONS: '.github/**, .vscode/**, android/**, assets/**, build/**, ios/**, node_modules/**, scripts/**, **/*.java, **/*.typegen.ts, __mocks__/**'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      ORG_KEY: ${{ secrets.ORG_KEY }}
      SLACK_WEBHOOK_URL: '${{ secrets.SLACK_WEBHOOK_INJI_TEAM }}'
